// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SillyString.Models;

#nullable disable

namespace ElectronicsVendor.Migrations
{
    [DbContext(typeof(SillyStringContext))]
    partial class SillyStringContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("SillyString.Models.Egineer", b =>
                {
                    b.Property<int>("EgineerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Manufacturer")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .HasColumnType("longtext");

                    b.HasKey("EgineerId");

                    b.ToTable("Egineers");
                });

            modelBuilder.Entity("SillyString.Models.EgineerMachine", b =>
                {
                    b.Property<int>("EgineerMachineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("EgineerId")
                        .HasColumnType("int");

                    b.Property<int>("MachineId")
                        .HasColumnType("int");

                    b.HasKey("EgineerMachineId");

                    b.HasIndex("EgineerId");

                    b.HasIndex("MachineId");

                    b.ToTable("EgineerMachines");
                });

            modelBuilder.Entity("SillyString.Models.Machine", b =>
                {
                    b.Property<int>("MachineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.HasKey("MachineId");

                    b.ToTable("Machines");
                });

            modelBuilder.Entity("SillyString.Models.EgineerMachine", b =>
                {
                    b.HasOne("SillyString.Models.Egineer", "Egineer")
                        .WithMany("JoinEntities")
                        .HasForeignKey("EgineerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SillyString.Models.Machine", "Machine")
                        .WithMany("JoinEntities")
                        .HasForeignKey("MachineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Egineer");

                    b.Navigation("Machine");
                });

            modelBuilder.Entity("SillyString.Models.Egineer", b =>
                {
                    b.Navigation("JoinEntities");
                });

            modelBuilder.Entity("SillyString.Models.Machine", b =>
                {
                    b.Navigation("JoinEntities");
                });
#pragma warning restore 612, 618
        }
    }
}
